# Generated by Django 2.0.4 on 2018-04-19 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busruta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busruta',
            name='empresa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='busempresa.BusEmpresa'),
        ),
    ]
