# Generated by Django 2.0.3 on 2018-04-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busparada', '0005_remove_busparada_ruta'),
        ('busruta', '0002_auto_20180419_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busruta',
            name='empresa',
        ),
        migrations.AddField(
            model_name='busruta',
            name='paradas',
            field=models.ManyToManyField(to='busparada.BusParada'),
        ),
    ]
