# Generated by Django 2.0.3 on 2018-04-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busruta', '0003_auto_20180419_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busruta',
            old_name='final',
            new_name='latitud_final',
        ),
        migrations.RenameField(
            model_name='busruta',
            old_name='inicio',
            new_name='longitud_final',
        ),
    ]
