# Generated by Django 2.0.3 on 2018-04-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busdriver', '0002_busdriver_empresa'),
        ('busempresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busempresa',
            name='choferes',
            field=models.ManyToManyField(to='busdriver.BusDriver'),
        ),
    ]
