# Generated by Django 2.0.4 on 2018-04-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(default='', max_length=255)),
                ('rating', models.SmallIntegerField(default=0)),
                ('latitud', models.FloatField(blank=True, default=None, null=True)),
                ('longitud', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
