# Generated by Django 2.0.3 on 2018-04-19 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busempresa', '0001_initial'),
        ('busdriver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdriver',
            name='empresa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='busempresa.BusEmpresa'),
        ),
    ]
