# Generated by Django 2.0.3 on 2018-04-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busruta', '0003_auto_20180419_1521'),
        ('busdriver', '0002_busdriver_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busdriver',
            name='empresa',
        ),
        migrations.AddField(
            model_name='busdriver',
            name='rutas',
            field=models.ManyToManyField(to='busruta.BusRuta'),
        ),
    ]
