# Generated by Django 2.0.3 on 2018-04-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busdriver', '0003_auto_20180419_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdriver',
            name='placa',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
