# Generated by Django 2.0.4 on 2018-04-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bususer', '0002_bususer_is_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bususer',
            name='is_driver',
        ),
    ]
