# Generated by Django 2.0.4 on 2018-04-19 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busparada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busparada',
            name='ruta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='busruta.BusRuta'),
        ),
    ]
