# Generated by Django 2.0.4 on 2018-04-19 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busparada', '0002_auto_20180419_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busparada',
            name='ruta',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='busruta.BusRuta'),
        ),
    ]
