# Generated by Django 2.0.3 on 2018-04-19 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busparada', '0004_auto_20180419_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busparada',
            name='ruta',
        ),
    ]
